# For local development, only database is running
#
# docker compose up -d
# uvicorn app.main:app --reload
#

services:
  postgres_db:
    restart: unless-stopped
    image: postgres:17
    volumes:
      - postgres_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DATABASE__DB}
      - POSTGRES_USER=${DATABASE__USERNAME}
      - POSTGRES_PASSWORD=${DATABASE__PASSWORD}
    env_file:
      - .env
    ports:
      - "${DATABASE__PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
#  fastapi:
#    build: .
#    env_file:
#      - ./.env
#    environment:
#      PYTHONPATH: .
#      DATABASE__HOSTNAME: postgres_db
#      DATABASE__PORT: 5432
#    depends_on:
#      postgres_db:
#        condition: service_healthy
#    ports:
#      - "8008:8008"
volumes:
  postgres_db:
