# For local development, only database is running
#
# docker compose up -d
# uvicorn app.main:app --reload
#

services:
  postgres_db:
    restart: unless-stopped
    image: postgres:17
    volumes:
      - postgres_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DATABASE__DB}
      - POSTGRES_USER=${DATABASE__USERNAME}
      - POSTGRES_PASSWORD=${DATABASE__PASSWORD}
    env_file:
      - .env
    ports:
      - "${DATABASE__PORT}:5432"
#  backend:
#    build:
#      context: backend
#      dockerfile: Dockerfile
#    command: python app/main.py
#    tty: true
#    volumes:
#      - ./backend:/backend/:cached
#      - ./.docker/.ipython:/root/.ipython:cached
#    environment:
#      PYTHONPATH: .
#      DATABASE_URL: "postgresql+asyncpg://dev-user:password@postgres:5432/dev_db"
#    depends_on:
#      - "postgres_db"
#    ports:
#      - 8000:8000
volumes:
  postgres_db:
